### ISSUE TITLE
The extracted preprocessed feature is super big

### ISSUE THREAD

**Issue by ElegantLin** [GLAMOR-USC/teach_tatc#1]
Hi, I am extracting the pre-processed feature and it is super big, which is over several TB. The extraction command I use is `tar zxvf **.tar.gz`. Could you please help me with this?

Thanks!

**Comment by ishikasingh** [comment]
Hi,
The data shouldn't be that big, the total download size is around 130GB. The extraction might take some time, but the command looks right.

**Comment by ElegantLin** [comment]
After extraction, I found the largest file is data.mdb, which is 700GB for every file. May I ask whether it is really that big?

Thanks!

**Comment by ishikasingh** [comment]
Hi, can you do `du -sh .` inside the extracted feature dir? It shouldn't be that big, those are precomputed image features.

**Comment by ElegantLin** [comment]
Here is the preview of the folder. I cannot extract all of them so I cannot execute `du -sh .` inside the extracted feature dir.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/16239478/164987720-231ce414-97b7-4b05-a53f-4ce192dacb45.png">

I think the size is much more different than yours. Could you please tell me the actual size of the feature before compressing them?

Thanks for your help!

**Comment by ishikasingh** [comment]
I tried to extract the features at my end, there seems to be an issue with extracting mdb files. I would suggest you to try and do data preprocessing at your end (as given in the README in this [section](https://github.com/GLAMOR-USC/teach_tatc#training)), while we try to fix this issue.

**Comment by ElegantLin** [comment]
Thanks a lot! Please let me know when you finish fixing it.
