### ISSUE TITLE
Invalid line while taking target_image in Data_util.py

### ISSUE THREAD

**Issue by jeje910** [GLAMOR-USC/teach_tatc#10]
Hello, 
I found a line that seems weird and share this information to check whether I got some misunderstanding or should be fixed.

As far as i know, the agent_id should be 0 or 1, so it cannot be reachable to 500.
And from this line, I think the code should be change to "action_id" (because action ID 501 and 502 are about the searching API)
        
https://github.com/GLAMOR-USC/teach_tatc/blob/e19fef1ca12fe225701036a16093bc2f3d92b3f0/src/teach/modeling/utils/data_util.py#L48

And also, The target_idx (variable "i" in below) also seems not valid. (I just fixed it for my own but for information)

https://github.com/GLAMOR-USC/teach_tatc/blob/e19fef1ca12fe225701036a16093bc2f3d92b3f0/src/teach/modeling/utils/data_util.py#L51

Thanks!

**Comment by ishikasingh** [comment]
Thanks for pointing out! You are right, those variables should be `"agent_id"`-->`"action_id"` and `i`-->`interaction`.

**Comment by jeje910** [comment]
Thank you for your reply! BTW, I have another question.

As the explanation in the paper, it seems we could get the ground truth of segmentation for target object.

![image](https://user-images.githubusercontent.com/64236071/194965196-e3243f73-d213-445f-8d5b-9c92560009c5.png)

But in the dataset I downloaded looks like below unlike the paper.

![image](https://user-images.githubusercontent.com/64236071/194965059-69754a74-4dba-42c9-a661-a70014bd580a.png)

I think something goes wrong and try to download the dataset again but seems hard to redownload it. 
(Downloading meta-data from google drive always fail due to network error)

Is the dataset I got wrong? And if so, could you please check whether the meta_data.tar.gz file could be downloaded normally?

Thanks!

**Comment by thomason-jesse** [comment]
Thanks for bringing this up! I have pushed a fix for this bug now, and the segmentation masks should render correctly on replay. Let me know if the bug persists after pulling 634c01145069007f0bdb245617daa8ecde5c092e and how to produce it if so.
