### ISSUE TITLE
Invalid line in transformer.py

### ISSUE THREAD

**Issue by terateil** [GLAMOR-USC/teach_tatc#11]
Hello, I guess I found small error in the code. In line 218,

https://github.com/GLAMOR-USC/teach_tatc/blob/5c8194ae5eda499137bf8e71c7a040cfb480c651/src/teach/modeling/models/ET/transformer.py#L218

I get error that there is no such argument `object_loss_wt`, while training the ET model.

In the config file
https://github.com/GLAMOR-USC/teach_tatc/blob/5c8194ae5eda499137bf8e71c7a040cfb480c651/src/teach/modeling/models/ET/configs.py#L55-L56

So I guess the  `object_loss_wt` in line 218 should be replaced with `action_aux_loss_wt`.
Thanks!

**Comment by aliang8** [comment]
Yes you're right, line 218 should be `losses["object"] = object_loss * self.args.action_aux_loss_wt`.

**Comment by terateil** [comment]
Thanks for your reply!
