### ISSUE TITLE
Gdown not working for metadata file

### ISSUE THREAD

**Issue by jiminsun** [GLAMOR-USC/teach_tatc#12]
Hi, thank you for sharing and maintaining the code to train TATC models in TEACh.

While following the instructions, I faced an issue where the gdown isn't working for the metadata file.
```
gdown --id 1vUhYmHRzNdCEG7CeIY96IvYLCaguQMKv
/custom/conda/lib/python3.8/site-packages/gdown/cli.py:126: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Access denied with the following error:

        Too many users have viewed or downloaded this file recently. Please
        try accessing the file again later. If the file you are trying to
        access is particularly large or is shared with many people, it may
        take up to 24 hours to be able to view or download the file. If you
        still can't access a file after 24 hours, contact your domain
        administrator.

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1vUhYmHRzNdCEG7CeIY96IvYLCaguQMKv
```
I've tried different troubleshooting methods suggested online (e.g., upgrading the gdown package, creating a copy of the file in google drive and using my link) but haven't been able to solve this issue.
Would it be possible to check whether this command still works?

**Comment by thomason-jesse** [comment]
Can you try again now? I am able to access the file via browser and manually do the download. As the error states, this is probably some rate limit issue with gDrive as opposed to something we can fix on our end.

**Comment by jiminsun** [comment]
Hi, thanks for the reply!
I have tried it again, and it seems to work well now. I guess it's some quota issue with gdown.
Thanks :)
