### ISSUE TITLE
Data preprocessing takes very large disk space

### ISSUE THREAD

**Issue by UeFan** [GLAMOR-USC/teach_tatc#3]
Hi, since as reported #1 , I am trying to do the data preprocessing from scratch. However, I find that doing data preprocessing will also generate super large lmdb files, each about 700GB. The reason is that in this line of code: https://github.com/GLAMOR-USC/teach_tatc/blob/06fe07037b4d8dccaed853d395d9a920e3e3cd10/src/teach/modeling/utils/data_util.py#L106, it is creating a lmdb file of size 700 * 1024**3. Is creating this large lmdb file on purpose?  

Thanks

**Comment by ishikasingh** [comment]
Please refer to #2
