### ISSUE TITLE
"Progress check not found" on data preprocessing

### ISSUE THREAD

**Issue by yingShen-ys** [GLAMOR-USC/teach_tatc#4]
Hi,

I have seen multiple "Progress check not found..." messages when performing data preprocessing. Is it normal or does something go wrong?

Also, if I have downloaded ` tatc_preprocessed_data.tar.gz`, do I still need to run the preprocessing? 

Thanks!

**Comment by UeFan** [comment]
I find the same issue. I suspect that it is because in [here](https://github.com/GLAMOR-USC/teach_tatc/blob/06fe07037b4d8dccaed853d395d9a920e3e3cd10/build/lib/teach/inference/inference_runner.py#L158) the `create_task_thor_from_state_diff(game["state_changes"])` returns a empty task and then the progress_check will fail.

**Comment by UeFan** [comment]
I think this is due to using the wrong dataset. You should use the game folder extracted from TATC dataset, instead of the game folder in TEACh dataset.

**Comment by yingShen-ys** [comment]
> I think this is due to using the wrong dataset. You should use the game folder extracted from TATC dataset, instead of the game folder in TEACh dataset.

I am actually using the game folder from TATC dataset. I only saw around 20 lines of this message (pasted below), I think I would get much more messages if I were using the game folder from TEACh.

```
Progress check not found...
Progress check not found...
Progress check not found...
Progress check not found...
Progress check not found...
 32% (747 of 2275) |################################                                                                   | Elapsed Time: 0:00:27 ETA:   0:00:53Progress check not found...
Progress check not found...
Progress check not found...
Progress check not found...
Progress check not found...
Progress check not found...
Progress check not found...
Progress check not found...
Progress check not found...
Progress check not found...
Progress check not found...
Progress check not found...
Progress check not found...
Progress check not found...
Progress check not found...
```

**Comment by UeFan** [comment]
oh yes, I remember that I also got this limited amount of "Progress check not found" too.

**Comment by ishikasingh** [comment]
Thanks for pointing it out. It seems a few files had some issues. We updated the dataset on the gdrive, you may run `download_data.sh` again to get the updated version.

**Comment by yingShen-ys** [comment]
> Thanks for pointing it out. It seems a few files had some issues. We updated the dataset on the gdrive, you may run `download_data.sh` again to get the updated version.

Got it, thank you!
