### ISSUE TITLE
About TATC Baselines

### ISSUE THREAD

**Issue by 594zyc** [GLAMOR-USC/teach_tatc#5]
Hi,

There are two questions: 
(1) Could you release the implementation of the rule-based baseline introduced in the TEACh paper? 
(2) Is there any result from the released seq2seq baseline model? Due to the data issue we are not able to reproduce the training, while still curious about its performance. 

Thanks!

**Comment by thomason-jesse** [comment]
1) Unfortunately, the rule-based agents code is still proprietary code. It's possible we'll be able to make it public in the future.

2) We're actively working towards such results. The current seq2seq baseline implementation gets zero percent on held out validation data. We'll release more stable/reasonable code as we finish it, with non-zero results when they're achieved for reference.

**Comment by 594zyc** [comment]
Get it. Thanks!
