### ISSUE TITLE
 Need more helper functions for getting target object positions&segmentations

### ISSUE THREAD

**Issue by UeFan** [GLAMOR-USC/teach_tatc#7]
Hi, I saw you have added the helper function for providing driver and commander positions. I think that there are other helper functions needed:

1. Currently, the SearchObject and SelectOid returns normalized position (normalized according to the room map, eg. (1, 1) if the object is on a corner of the room). However, I find that the returned position of the agents are real positions, eg. (1.5, -0.5). In this case I think a helper function to transfer a normalized position to real position is needed. Or, maybe just rewrite the SearchObject and SelectOid to return real positions instead of normalized position. 
2.  I think according to the TEACh paper,  the commander should be able to know where the target object is in the follower's view. For example, when the follower saw a pot, the commander should be able to know  the ground truth bounding box/segmentation for that pot in follower's view.

**Comment by thomason-jesse** [comment]
1) I agree, we will make this change.

2) The Commander has access to the RGB frame viewed by the Follower, not ground truth bounding box or segmentation masks. Object segmentation masks are exclusively accessible to the Commander via the SearchObject API call, and are not accessible to the Follower. The Commander is free, though, to run an object detection module on the Follower RGB frame.

**Comment by UeFan** [comment]
@thomason-jesse Thanks! 

For 2, if I understand you correctly, the setting should be: 
a) The Commander can only access the ground truth object segmentation mask for a certain "searched" object through API call.
b) Without using API call, Commander has no access to ground truth segmentation. 

Is these correct?

So if it's correct, I think, still, more helper function is needed because I find the return of SearchObject and SelectOid API call won't return the object segemention in driver's view, but only a object segmentation in an object-camera's perspective, which I believe is not really helpful.

**Comment by thomason-jesse** [comment]
Your understanding is correct.

We do not have an API call that allows the Commander to get an exact segmentation mask of objects in the Driver's view. Such an API call would remove the need to do any visual understanding at all from the Commander side. As during human data collection, the Commander can use the SearchObject call to get the relative position of the object with respect to the Follower as well as its visual appearance in order to form natural language descriptions and instructions to the Follower. The API is designed to mimic as closely as possible the simulator data available to the human annotators during data collection.

**Comment by UeFan** [comment]
I see. Then my question is, in the TEACh paper Section 5.2, I find that the commander in rule-based TATC baseline has the ability to provide the (x,y) screen click positions for interaction actions. Since the baseline is non-learning according to the paper, how is it possible for the baseline Commander to know the screen click positions?

**Comment by thomason-jesse** [comment]
From my memory, the rule based Commander in the TEACh paper uses the SearchObject API call on the object of interest and assumes (possibly incorrectly!) that the returned mask will be "close enough" to what the Driver is seeing after the Driver follows the specified navigation actions.

**Comment by UeFan** [comment]
Got it. Thank you very much! Hope that the rule-based baseline code can be released in the future.
