### ISSUE TITLE
Can we use pre-trained model for commander for TATC challenge?

### ISSUE THREAD

**Issue by jeje910** [GLAMOR-USC/teach_tatc#8]
In EAI, CVPR 2022 the rule of commander is that

"Commander agents are free to use all the metadata returned by ProgressCheck and SearchObject actions (e.g., object segmentation masks and map locations), and RGB inputs from the Commander, Follower, and Object Search cameras."

But in case of E.T. model, it used OSCAR model to deal with ALFRED challenge.
So, as the title of this issue, is it okay for us to use some other pre-trained model for this challenge?

Thank you!

**Comment by thomason-jesse** [comment]
Yes, you can use pre-trained models such as OSCAR as part of the TEACh challenge. You can also use models that were trained on the ALFRED data. The relevant restriction is just on the input data used. Since you can use Commander and Follower RGB frames and dialogue history, OSCAR is fine.

**Comment by jeje910** [comment]
Thank you for your kind reply! It was very helpful for me to understand this task more!
